version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres
    container_name: we_exchange_db
    env_file: ./backend/.env
    ports:
      - "5432:5432"
